# Charminal shell integration (OSC 133) for bash
#
# auto-generated by Charminal at startup. Do not edit; user の拡張は
# ~/.charminal/shell/user.bash に書くこと。

__charminal_preexec() {
    printf '\e]133;C\a'
}

__charminal_precmd() {
    local exit_code=$?
    printf '\e]133;D;%s\a' "$exit_code"
}

# bash には preexec hook が標準で無い。DEBUG trap を 1 度だけ設定する。
if [ -z "${__CHARMINAL_TRAPPED:-}" ]; then
    trap '__charminal_preexec' DEBUG
    __CHARMINAL_TRAPPED=1
fi

# PROMPT_COMMAND の先頭に precmd を chain（既に登録済みなら no-op）。
case "${PROMPT_COMMAND:-}" in
    *__charminal_precmd*) ;;
    "") PROMPT_COMMAND="__charminal_precmd" ;;
    *) PROMPT_COMMAND="__charminal_precmd; ${PROMPT_COMMAND}" ;;
esac
