# Charminal shell integration (OSC 133) for zsh
#
# auto-generated by Charminal at startup. Do not edit; user の拡張は
# ~/.yorishiro/shell/user.zsh に書くこと（こちらは init.zsh の後で source される）。
#
# precmd / preexec hook に append する形で OSC 133 の C / D marker と
# OSC 633 の command / cwd metadata を emit する。
# PROMPT 自体は触らない（p10k / oh-my-zsh / prezto との衝突を避ける）。

__yorishiro_osc633_escape() {
    emulate -L zsh
    local LC_ALL=C
    local input="$1"
    local out=""
    local i char hex
    for (( i = 1; i <= ${#input}; i++ )); do
        char="${input[i]}"
        case "$char" in
            [A-Za-z0-9_/:.,@%+=-])
                out+="$char"
                ;;
            *)
                printf -v hex '%02X' "'$char"
                out+="\\x$hex"
                ;;
        esac
    done
    printf '%s' "$out"
}

__yorishiro_emit_cwd() {
    printf '\e]633;P;Cwd=%s\a' "$(__yorishiro_osc633_escape "$PWD")"
}

__yorishiro_preexec() {
    printf '\e]633;E;%s\a' "$(__yorishiro_osc633_escape "$1")"
    printf '\e]133;C\a'
}

__yorishiro_precmd() {
    local exit_code=$?
    printf '\e]133;D;%s\a' "$exit_code"
    __yorishiro_emit_cwd
    printf '\e]7;file://%s\a' "$PWD"
}

# 重複登録を避ける（再 source / HMR ケース）
if [[ -z "${precmd_functions[(r)__yorishiro_precmd]:-}" ]]; then
    precmd_functions+=(__yorishiro_precmd)
fi
if [[ -z "${preexec_functions[(r)__yorishiro_preexec]:-}" ]]; then
    preexec_functions+=(__yorishiro_preexec)
fi

__yorishiro_path_prepend_unique_directory() {
    local directory="$1"
    local current="${2:-$PATH}"
    [[ -n "$directory" && -d "$directory" ]] || return 0
    local -a entries next
    entries=("${(@s/:/)current}")
    next=("$directory")
    local entry
    for entry in "${entries[@]}"; do
        [[ -z "$entry" || "$entry" == "$directory" ]] && continue
        next+=("$entry")
    done
    print -r -- "${(j/:/)next}"
}

__yorishiro_install_agent_shims() {
    local shim_root="${YORISHIRO_AGENT_SHIM_ROOT:-}"
    [[ -n "$shim_root" && -d "$shim_root" ]] || return 0

    PATH="$(__yorishiro_path_prepend_unique_directory "$shim_root" "${PATH-}")"
    export PATH
    hash -r >/dev/null 2>&1 || rehash >/dev/null 2>&1 || true

    builtin unalias claude >/dev/null 2>&1 || true
    builtin unalias codex >/dev/null 2>&1 || true

    if [[ -x "$shim_root/claude" ]]; then
        claude() { "$YORISHIRO_AGENT_SHIM_ROOT/claude" "$@"; }
    fi
    if [[ -x "$shim_root/codex" ]]; then
        codex() { "$YORISHIRO_AGENT_SHIM_ROOT/codex" "$@"; }
    fi
}

__yorishiro_install_agent_shims
