# Charminal shell integration (OSC 133) for bash
#
# auto-generated by Charminal at startup. Do not edit; user の拡張は
# ~/.charminal/shell/user.bash に書くこと。

__charminal_osc633_escape() {
    local LC_ALL=C
    local input="$1"
    local out=""
    local i char hex
    for (( i = 0; i < ${#input}; i++ )); do
        char="${input:i:1}"
        case "$char" in
            [A-Za-z0-9_/:.,@%+=-])
                out+="$char"
                ;;
            *)
                printf -v hex '%02X' "'$char"
                out+="\\x$hex"
                ;;
        esac
    done
    printf '%s' "$out"
}

__charminal_emit_cwd() {
    printf '\e]633;P;Cwd=%s\a' "$(__charminal_osc633_escape "$PWD")"
}

__charminal_preexec() {
    local command="${1:-$BASH_COMMAND}"
    printf '\e]633;E;%s\a' "$(__charminal_osc633_escape "$command")"
    printf '\e]133;C\a'
}

__charminal_precmd() {
    local exit_code="${1:-$?}"
    printf '\e]133;D;%s\a' "$exit_code"
    __charminal_emit_cwd
    return "$exit_code"
}

__charminal_current_command_line() {
    local line
    line="$(HISTTIMEFORMAT= history 1)"
    line="${line#"${line%%[![:space:]]*}"}"
    local number_prefix="${line%%[!0-9]*}"
    if [ -n "$number_prefix" ]; then
        line="${line#"$number_prefix"}"
        line="${line#"${line%%[![:space:]]*}"}"
    fi
    printf '%s' "${line:-$BASH_COMMAND}"
}

__charminal_preexec_invoke_exec() {
    [ "${__charminal_preexec_ready:-0}" = "1" ] || return 0
    [ "${__charminal_in_preexec:-0}" = "0" ] || return 0
    case "$BASH_COMMAND" in
        __charminal_* | trap\ * | PROMPT_COMMAND=*)
            return 0
            ;;
    esac

    __charminal_preexec_ready=0
    __charminal_in_preexec=1
    __charminal_preexec "$(__charminal_current_command_line)"
    __charminal_in_preexec=0
}

__charminal_prompt_command() {
    local exit_code=$?
    __charminal_preexec_ready=0
    __charminal_precmd "$exit_code"
    local charminal_status=$?
    if [ -n "${__CHARMINAL_ORIGINAL_PROMPT_COMMAND:-}" ]; then
        ( exit "$exit_code" )
        eval "$__CHARMINAL_ORIGINAL_PROMPT_COMMAND"
    fi
    __charminal_preexec_ready=1
    return "$charminal_status"
}

# bash には preexec hook が標準で無い。PROMPT_COMMAND 後の最初の DEBUG だけを
# command line boundary として扱い、複合 command の simple command では emit しない。
if [ -z "${__CHARMINAL_TRAPPED:-}" ]; then
    __charminal_preexec_ready=0
    __charminal_in_preexec=0
    trap '__charminal_preexec_invoke_exec' DEBUG
    __CHARMINAL_TRAPPED=1
fi

# PROMPT_COMMAND は wrapper 関数に差し替える。init.bash source 前に user .bashrc が
# 設定していた command は wrapper 内で実行する。
if [ -z "${__CHARMINAL_PROMPT_COMMAND_INSTALLED:-}" ]; then
    __CHARMINAL_ORIGINAL_PROMPT_COMMAND="${PROMPT_COMMAND:-}"
    PROMPT_COMMAND="__charminal_prompt_command"
    __CHARMINAL_PROMPT_COMMAND_INSTALLED=1
fi

__charminal_path_prepend_unique_directory() {
    local directory="$1"
    local current="${2:-$PATH}"
    [ -n "$directory" ] && [ -d "$directory" ] || return 0
    local old_ifs="$IFS"
    local next="$directory"
    local entry
    IFS=:
    for entry in $current; do
        [ -z "$entry" ] && continue
        [ "$entry" = "$directory" ] && continue
        next="$next:$entry"
    done
    IFS="$old_ifs"
    printf '%s\n' "$next"
}

__charminal_install_agent_shims() {
    local shim_root="${CHARMINAL_AGENT_SHIM_ROOT:-}"
    [ -n "$shim_root" ] && [ -d "$shim_root" ] || return 0

    PATH="$(__charminal_path_prepend_unique_directory "$shim_root" "${PATH-}")"
    export PATH
    hash -r >/dev/null 2>&1 || true

    unalias claude >/dev/null 2>&1 || true
    unalias codex >/dev/null 2>&1 || true

    if [ -x "$shim_root/claude" ]; then
        claude() { "$CHARMINAL_AGENT_SHIM_ROOT/claude" "$@"; }
    fi
    if [ -x "$shim_root/codex" ]; then
        codex() { "$CHARMINAL_AGENT_SHIM_ROOT/codex" "$@"; }
    fi
}

__charminal_install_agent_shims
