# Yorishiro shell integration (OSC 133) for fish
#
# auto-generated by Yorishiro at startup. Do not edit; user の拡張は
# ~/.yorishiro/shell/user.fish に書くこと。

function __yorishiro_osc633_escape --argument-names input
    set -l out ""
    for byte in (printf '%s' "$input" | od -An -v -tx1 | string split ' ' | string match -r '^[0-9a-f][0-9a-f]$')
        set out "$out\\x"(string upper "$byte")
    end
    printf '%s' "$out"
end

function __yorishiro_emit_cwd
    printf '\e]633;P;Cwd=%s\a' (__yorishiro_osc633_escape "$PWD")
end

function __yorishiro_preexec --on-event fish_preexec --argument-names commandline
    printf '\e]633;E;%s\a' (__yorishiro_osc633_escape "$commandline")
    printf '\e]133;C\a'
end

function __yorishiro_postexec --on-event fish_postexec
    printf '\e]133;D;%s\a' $status
    __yorishiro_emit_cwd
    printf '\e]7;file://%s\a' "$PWD"
end

function __yorishiro_path_prepend_unique_directory --argument-names directory
    test -n "$directory"; and test -d "$directory"; or return 0
    set -l next_path "$directory"
    for entry in $PATH
        test -z "$entry"; and continue
        test "$entry" = "$directory"; and continue
        set -a next_path "$entry"
    end
    set -gx PATH $next_path
end

function __yorishiro_install_agent_shims
    set -q YORISHIRO_AGENT_SHIM_ROOT; or return 0
    test -n "$YORISHIRO_AGENT_SHIM_ROOT"; and test -d "$YORISHIRO_AGENT_SHIM_ROOT"; or return 0

    __yorishiro_path_prepend_unique_directory "$YORISHIRO_AGENT_SHIM_ROOT"

    functions -e claude >/dev/null 2>&1
    functions -e codex >/dev/null 2>&1

    if test -x "$YORISHIRO_AGENT_SHIM_ROOT/claude"
        function claude
            "$YORISHIRO_AGENT_SHIM_ROOT/claude" $argv
        end
    end
    if test -x "$YORISHIRO_AGENT_SHIM_ROOT/codex"
        function codex
            "$YORISHIRO_AGENT_SHIM_ROOT/codex" $argv
        end
    end
end

__yorishiro_install_agent_shims
