# Charminal shell integration (OSC 133) for fish
#
# auto-generated by Charminal at startup. Do not edit; user の拡張は
# ~/.charminal/shell/user.fish に書くこと。

function __charminal_preexec --on-event fish_preexec
    printf '\e]133;C\a'
end

function __charminal_postexec --on-event fish_postexec
    printf '\e]133;D;%s\a' $status
end
