# Charminal shell integration (OSC 133) for zsh
#
# auto-generated by Charminal at startup. Do not edit; user の拡張は
# ~/.charminal/shell/user.zsh に書くこと（こちらは init.zsh の後で source される）。
#
# precmd / preexec hook に append する形で OSC 133 の C / D marker を emit する。
# PROMPT 自体は触らない（p10k / oh-my-zsh / prezto との衝突を避ける）。

__charminal_preexec() {
    printf '\e]133;C\a'
}

__charminal_precmd() {
    local exit_code=$?
    printf '\e]133;D;%s\a' "$exit_code"
}

# 重複登録を避ける（再 source / HMR ケース）
if [[ -z "${precmd_functions[(r)__charminal_precmd]:-}" ]]; then
    precmd_functions+=(__charminal_precmd)
fi
if [[ -z "${preexec_functions[(r)__charminal_preexec]:-}" ]]; then
    preexec_functions+=(__charminal_preexec)
fi
